/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#ffffff';

export const Colors = {
	light: {
		bim: '#EE8438',
		yellow: '#FDB529',
		lime: '#72E128',
		lightBlue: '#29C5F9',
		secondaryButton: '#6D788D',
		screenTitleText: '#636578',
		actionButton: '#F59E0C',
		cancelButton: '#6D788D',
		dangerButton: '#FF3B30',
		buttonError: '#5A5FE0',
		headerIcons: '#636578',
		drawerItem: '#636578',
		titleBg: '#E1E2FF',
		headerBackground: '#ffffff',
		dayTransactionsBackground: '#F0F9FF',
		weekTransactionsBackground: '#FEF9F3',
		monthTransactionsBackground: '#EEF9F1',
		'heading.one': '#636578',
		valueText: 'rgb(75, 75, 75)',
		mutedText: '#B5B8BF',
		dayIconBackground: '#3C82F6',
		weekIconBackground: '#F0B90B',
		monthIconBackground: '#12B981',
		dayText: '#EE8438',
		weekText: '#FDB529',
		monthText: '#72E128',
		headerDropdownBackground: '#ffffff',
		text: '#828393',
		error: '#FF3B30',
		white: '#ffffff',
		border: '#4c4e640d',
		borderDark: '#ddd',
		authButtonText: '#ffffff',
		focusedInput: '#0a7ea4',
		drawerBackground: '#ffffff',
		drawerButtonBackground: '#ffffff',
		drawerActiveBackground: '#a9a9a90f',
		drawerInactiveItem: '#636578',
		listItemBackground: '#F5F5F7',
		languageButtonBackground: '#F0F0FF',
		inputBackground: '#F5F5F7',
		inputContainerBackground: '#ffffff',
		inputBorder: '#E0E0E0',
		background: '#ffffff',
		tint: tintColorLight,
		iconTint: '#ffffff',
		notificationsCount: '#6D788D',
		notificationsCountBackground: '#E9EBEE',
		tabIconDefault: '#687076',
		tabIconSelected: tintColorLight,
		headers: '#636578',
	},
	dark: {
		bim: '#EE8438',
		yellow: '#FDB529',
		lime: '#72E128',
		lightBlue: '#29C5F9',
		secondaryButton: '#6D788D',
		screenTitleText: '#636578',
		actionButton: '#F59E0C',
		cancelButton: '#6D788D',
		dangerButton: '#FF3B30',
		buttonError: '#5A5FE0',
		headerIcons: '#636578',
		drawerItem: '#636578',
		titleBg: '#E1E2FF',
		headerBackground: '#ffffff',
		dayTransactionsBackground: '#F0F9FF',
		weekTransactionsBackground: '#FEF9F3',
		monthTransactionsBackground: '#EEF9F1',
		'heading.one': '#636578',
		valueText: 'rgb(75, 75, 75)',
		mutedText: '#B5B8BF',
		dayIconBackground: '#3C82F6',
		weekIconBackground: '#F0B90B',
		monthIconBackground: '#12B981',
		dayText: '#EE8438',
		weekText: '#FDB529',
		monthText: '#72E128',
		headerDropdownBackground: '#ffffff',
		text: '#828393',
		error: '#FF3B30',
		border: '#4c4e640d',
		borderDark: '#ddd',
		white: '#ffffff',
		authButtonText: '#ffffff',
		focusedInput: '#0a7ea4',
		drawerBackground: '#ffffff',
		drawerButtonBackground: '#ffffff',
		drawerActiveBackground: '#a9a9a90f',
		drawerInactiveItem: '#636578',
		listItemBackground: '#F5F5F7',
		languageButtonBackground: '#F0F0FF',
		inputBackground: '#F5F5F7',
		inputBorder: '#E0E0E0',
		inputContainerBackground: '#ffffff',
		background: '#ffffff',
		tint: tintColorDark,
		iconTint: '#ffffff',
		notificationsCount: '#6D788D',
		notificationsCountBackground: '#E9EBEE',
		tabIconDefault: '#9BA1A6',
		tabIconSelected: tintColorDark,
		headers: '#636578',
	},
};
