/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
	light: {
		bim: '#EE8438',
		buttonError: '#5A5FE0',
		headerIcons: '#636578',
		drawerItem: '#636578',
		headerBackground: '#fff',
		dayTransactionsBackground: '#F0F9FF',
		weekTransactionsBackground: '#FEF9F3',
		monthTransactionsBackground: '#EEF9F1',
		'heading.one': '#636578',
		headerDropdownBackground: '#fff',
		text: '#828393',
		error: '#FF3B30',
		border: 'rgba(76, 78, 100, 0.05)',
		authButtonText: '#fff',
		focusedInput: '#0a7ea4',
		drawerBackground: '#ffffff',
		drawerButtonBackground: '#ffffff',
		drawerActiveBackground: '#e4e4e40f',
		listItemBackground: '#F5F5F7',
		languageButtonBackground: '#F0F0FF',
		inputBackground: '#F5F5F7',
		inputContainerBackground: '#ffffff',
		inputBorder: '#E0E0E0',
		background: '#fff',
		tint: tintColorLight,
		icon: '#687076',
		notificationsCount: '#6D788D',
		notificationsCountBackground: '#E9EBEE',
		tabIconDefault: '#687076',
		tabIconSelected: tintColorLight,
		headers: '#636578',
	},
	dark: {
		bim: '#EE8438',
		buttonError: '#5A5FE0',
		headerIcons: '#636578',
		drawerItem: '#636578',
		headerBackground: '#fff',
		dayTransactionsBackground: '#F0F9FF',
		weekTransactionsBackground: '#FEF9F3',
		monthTransactionsBackground: '#EEF9F1',
		'heading.one': '#636578',
		headerDropdownBackground: '#fff',
		text: '#828393',
		error: '#FF3B30',
		border: 'rgba(76, 78, 100, 0.05)',
		authButtonText: '#fff',
		focusedInput: '#0a7ea4',
		drawerBackground: '#ffffff',
		drawerButtonBackground: '#ffffff',
		drawerActiveBackground: '#e4e4e40f',
		listItemBackground: '#F5F5F7',
		languageButtonBackground: '#F0F0FF',
		inputBackground: '#F5F5F7',
		inputBorder: '#E0E0E0',
		inputContainerBackground: '#ffffff',
		background: '#151718',
		tint: tintColorDark,
		icon: '#9BA1A6',
		notificationsCount: '#6D788D',
		notificationsCountBackground: '#E9EBEE',
		tabIconDefault: '#9BA1A6',
		tabIconSelected: tintColorDark,
		headers: '#636578',
	},
};
