import { TextStyle } from 'react-native';
export const fontSize: Record<string, number> = {
	'heading.one': 22,
	'heading.two': 18,
	'heading.three': 16,
	'button.large': 16,
	'button.medium': 14,
	'button.small': 12,
	'text.large': 16,
	'text.medium': 14,
	'text.small': 12,
	'text.xsmall': 10,
	'input.large': 16,
	'input.medium': 14,
	'input.small': 12,
	'input.xsmall': 10,
	'label.large': 16,
	'label.medium': 14,
	'label.small': 12,
	'label.xsmall': 10,
	'notification.title': 16,
	'notification.body': 14,
};
export const fontWeight: Record<string, TextStyle['fontWeight']> = {
	'heading.one': '500',
	'heading.two': '500',
	'heading.three': '400',
	'button.large': '500',
	'button.medium': '500',
	'button.small': '500',
	'text.large': '400',
	'text.medium': '400',
	'text.small': '400',
	'text.xsmall': '400',
};
