import { Translations } from '@/types';

const translations: Translations = {
	en: {
		name: 'English',
		active: true, // Set to true only if fully translated
		categories: {
			auth: {
				'signUp.title': 'Adventure starts here 🚀',
				'signUp.subtitle': 'Make your hotspot management easy and fun!',
				'signIn.title': 'Welcome to BIM Networks!👋',
				'signIn.subtitle':
					'Please sign-in to your account and start the adventure',
				'verify.title': 'Login Verification 👋',
				'verify.subtitle': 'Please enter the OTP code sent to your phone',
				fullName: 'Full Name',
				phoneNumber: 'Phone Number',
				password: 'Password',
				email: 'Email',
				confirmPassword: 'Confirm Password',
				signIn: 'Sign In instead',
				signUp: 'Sign Up instead',
				enterOTP: 'Enter OTP',
				haveAnAccount: 'Already have an account?',
				forgotPassword: 'Forgot Password?',
			},
			buttons: {
				verifyOTP: 'Verify OTP',
				signIn: 'Sign In',
				signUp: 'Sign Up',
				allTransactions: 'View All Transactions',
				allVoucherUsers: 'View All Voucher Users',
				createSingleVoucher: 'Create Single Voucher',
				createBulkVouchers: 'Create Bulk Vouchers',
				generateUsersAndPdf: 'Generate users and pdf',
				confirm: 'Confirm',
				downloadCSV: 'Download CSV',
				viewUsers: 'View Users',
				addRouter: 'Add Router',
				saveRouter: 'Save Router',
				editRouter: 'Edit Router',
				deleteRouter: 'Delete Router',
				updateRouter: 'Update Router',
				viewPackages: 'View Packages',
				viewVouchers: 'View Vouchers',
				saveChanges: 'Save Changes',
				hotspots: 'Hotspots',
				cancel: 'Cancel',
				delete: 'Delete',
				close: 'Close',
				ok: 'OK',
				block: 'Block',
				apply: 'Apply',
				save: 'Save',
			},
			navigation: {
				home: 'Dashboard',
				settings: 'Settings',
				routers: 'Routers',
				transactions: 'Transactions',
				packages: 'Packages',
				vouchers: 'Vouchers',
				banks: 'Banks',
				documents: 'Documents',
				profile: 'My Profile',
				notifications: 'Notifications',
				about: 'About',
				help: 'Help',
				logout: 'Logout',
			},
			notifications: {
				title: 'Notifications',
				new: 'New',
				'no.notifications': 'No new notifications available',
				seeAll: 'View All Notifications',
			},
			routers: {
				id: 'ID',
				hotspotName: 'Hotspot Name',
				interface: 'Interface',
				profile: 'Profile',
				status: 'Status',
				actions: 'Actions',
				title: 'Routers',
				editTitle: 'Edit Router',
				newTitle: 'Create Router',
				routerType: 'Router Type',
				routerHash: 'Router Hash',
				routerStatus: 'Router Status',
				uptime: 'Uptime',
				ipv4: 'IPv4 Address',
				ipv6: 'IPv6 Address',
				macAddress: 'MAC Address',
				location: 'Location',
				routerOS: 'RouterOS Version',
				freeMemory: 'Free Memory',
				totalMemory: 'Total Memory',
				cpuLoad: 'CPU Load',
				cpuFrequency: 'CPU Frequency',
				storage: 'Storage',
				firmwareVersion: 'Firmware Version',
				model: 'Model',
				hotspotsTitle: 'Hotspot Servers for Router',
				deleteMessage:
					'Are you sure you want to delete this router? This action cannot be undone.',
			},
			packages: {
				subtitle: 'Select router to view associated packages',
			},
			hotspots: {
				title: 'Hotspot Servers for Router:',
			},
			vouchers: {
				mainTitle: 'Routers',
				mainSubtitle: 'Select router to manage vouchers',
				vouchersSubtitle:
					'Vouchers for Hotspot Server: {hotspotName} on router: {routerName}',
				vouchers: 'Vouchers',
				package: 'Package',
				numberOfUsers: 'Number of Users',
				createHotspotVoucher: 'Create Hotspot Voucher',
				createHotspotVouchers: 'Create Hotspot Vouchers',
				status: 'Status',
				macAddress: 'MAC Address',
				uptime: 'Uptime',
				bytesIn: 'Bytes In',
				bytesOut: 'Bytes Out',
				actions: 'Actions',
				editVoucher: 'Edit Voucher: {voucher}',
				username: 'Username',
				password: 'Password',
				profile: 'Profile',
				confirmBlockTitle: 'Confirm Block User',
				blockMessage:
					'Are you sure you want to block this user? They will no longer be able to access the hotspot.',
				confirmDeleteTitle: 'Confirm Delete User',
				deleteMessage:
					'Are you sure you want to delete this user? This action cannot be undone.',
			},
			dashboard: {
				title: 'Dashboard',
				todaysTransactions: "Today's Transactions",
				weeksTransactions: "This Week's Transactions",
				monthsTransactions: "This Month's Transactions",
				todaysVouchers: "Today's Voucher Users",
				weeksVouchers: "This Week's Voucher Users",
				monthsVouchers: "This Month's Voucher Users",
				lastTransactions: 'last {number} transactions',
				transVolume: 'Transaction Volume (Last {number} days)',
				lastVouchers: 'Vouchers Users Created (Last {number} days)',
				amount: 'Amount',
				type: 'Type',
				reason: 'Reason',
				routerName: 'Router Name',
				routerUsername: 'Router Username',
				routerPassword: 'Router Password',
				routerBalances: 'Router Balances',
				confirmDeleteTitle: 'Confirm Delete',
				routerNamePlaceholder: 'eg. Router 01',
				date: 'Date',
				voucher: 'Voucher',
				package: 'Package',
				status: 'Status',
				ipAddress: 'IP Address',
				macAddress: 'MAC Address',
				name: 'Name',
				location: 'Location',
				actions: 'Actions',
				balance: 'Balance',
				uptime: 'Uptime',
				bytesIn: 'Bytes In',
				bytesOut: 'Bytes Out',
				loading: 'Loading...',
			},
		},
	},
	fr: {
		name: 'Français',
		active: false,
		categories: {
			auth: {},
		},
	},
	es: {
		name: 'Español',
		active: false,
		categories: {
			auth: {},
		},
	},
	de: {
		name: 'Deutsch',
		active: false,
		categories: {
			auth: {},
		},
	},
	it: {
		name: 'Italiano',
		active: false,
		categories: {
			auth: {},
		},
	},
	// Add other required languages with minimal structure
	pt: {
		name: 'Português',
		active: false,
		categories: {
			auth: {},
		},
	},
	ru: {
		name: 'Русский',
		active: false,
		categories: {
			auth: {},
		},
	},
	zh: {
		name: '中文',
		active: false,
		categories: {
			auth: {},
		},
	},
	ar: {
		name: 'العربية',
		active: false,
		categories: {
			auth: {},
		},
	},
	ja: {
		name: '日本語',
		active: false,
		categories: {
			auth: {},
		},
	},
};

export default translations;
